### ISSUE TITLE
 modbus usb stick niet beschikbaar

### ISSUE THREAD

**Issue by ezwep** [robertraaijmakers/com.iungo#10]
Hoi Robert,

Ik heb een iungo lite met een modbus usb stick met hieraan een Modbus SDM630 V2 kWh meter in gebruik om het gebruik van de laadpaal uit te lezen.
Nu werkt de iungo lite goed, maar de Modbus niet. In de Homey app is het apparaat wel zichtbaar maar ik kan er niks mee; hij geeft de melding: Apparaat niet beschikbaar.

Wordt dit niet ondersteund?

Alvast bedankt voor je reactie!

Mvg Erik

**Comment by robertraaijmakers** [comment]
Hi Erik,

In principe wordt de Iungo API gebruikt, ik betwijfel alleen wat voor type apparaat dit is en hoe deze beschikbaar gesteld wordt in de API van Iungo. Ik heb hem zelf niet in huis dus dat is lastig testen voor mij.

Zou jij de volgende URL kunnen aanroepen en het resultaat kunnen plaatsen?
http://<>/iungo/control/?cmd=api_form&method=objmgr_get_objects_with_values_and_metadata and post either all data (after clicking on the call method button) or only the part of the water meter.

Daarnaast ontvang ik graag een screenshot van de app met de naam van de meter en hoe je die selecteert.

Alvast bedankt, Robert

**Comment by ezwep** [comment]
Hoi Robert,

Hierbij het resultaat van de link:
{
   "objects": [
      {
         "driver": "button-gpio",
         "name": "-",
         "oid": "c430d9e0",
         "propsval": {},
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            }
         ],
         "uid": "button",
         "type": "button"
      },
      {
         "driver": "clock",
         "name": "-",
         "oid": "ce9577e3",
         "propsval": [
            {
               "id": "time",
               "value": "20:33"
            },
            {
               "id": "date",
               "value": "2019-07-16"
            },
            {
               "id": "timezone",
               "value": "Europe/Amsterdam"
            },
            {
               "id": "ntp_server",
               "value": "pool.ntp.org"
            },
            {
               "id": "ntp_status",
               "value": "ok, peer \"174.138.9.187\""
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "id": "time",
               "type": "string",
               "label": "Time"
            },
            {
               "id": "date",
               "type": "string",
               "label": "Date"
            },
            {
               "fn_set": null,
               "type": "enum",
               "default": "Europe/Amsterdam",
               "label": "Time zone",
               "id": "timezone",
               "writable": true,
               "range": "Africa/Abidjan,Africa/Accra,Africa/Addis_Ababa,Africa/Algiers,Africa/Asmara,Africa/Bamako,Africa/Bangui,Africa/Banjul,Africa/Bissau,Africa/Blantyre,Africa/Brazzaville,Africa/Bujumbura,Africa/Cairo,Africa/Casablanca,Africa/Ceuta,Africa/Conakry,Africa/Dakar,Africa/Dar_es_Salaam,Africa/Djibouti,Africa/Douala,Africa/El_Aaiun,Africa/Freetown,Africa/Gaborone,Africa/Harare,Africa/Johannesburg,Africa/Kampala,Africa/Khartoum,Africa/Kigali,Africa/Kinshasa,Africa/Lagos,Africa/Libreville,Africa/Lome,Africa/Luanda,Africa/Lubumbashi,Africa/Lusaka,Africa/Malabo,Africa/Maputo,Africa/Maseru,Africa/Mbabane,Africa/Mogadishu,Africa/Monrovia,Africa/Nairobi,Africa/Ndjamena,Africa/Niamey,Africa/Nouakchott,Africa/Ouagadougou,Africa/Porto-Novo,Africa/Sao_Tome,Africa/Tripoli,Africa/Tunis,Africa/Windhoek,America/Adak,America/Anchorage,America/Anguilla,America/Antigua,America/Araguaina,America/Argentina/Buenos_Aires,America/Argentina/Catamarca,America/Argentina/Cordoba,America/Argentina/Jujuy,America/Argentina/La_Rioja,America/Argentina/Mendoza,America/Argentina/Rio_Gallegos,America/Argentina/Salta,America/Argentina/San_Juan,America/Argentina/San_Luis,America/Argentina/Tucuman,America/Argentina/Ushuaia,America/Aruba,America/Asuncion,America/Atikokan,America/Bahia,America/Barbados,America/Belem,America/Belize,America/Blanc-Sablon,America/Boa_Vista,America/Bogota,America/Boise,America/Cambridge_Bay,America/Campo_Grande,America/Cancun,America/Caracas,America/Cayenne,America/Cayman,America/Chicago,America/Chihuahua,America/Costa_Rica,America/Cuiaba,America/Curacao,America/Danmarkshavn,America/Dawson,America/Dawson_Creek,America/Denver,America/Detroit,America/Dominica,America/Edmonton,America/Eirunepe,America/El_Salvador,America/Fortaleza,America/Glace_Bay,America/Godthab,America/Goose_Bay,America/Grand_Turk,America/Grenada,America/Guadeloupe,America/Guatemala,America/Guayaquil,America/Guyana,America/Halifax,America/Havana,America/Hermosillo,America/Indiana/Indianapolis,America/Indiana/Knox,America/Indiana/Marengo,America/Indiana/Petersburg,America/Indiana/Tell_City,America/Indiana/Vevay,America/Indiana/Vincennes,America/Indiana/Winamac,America/Inuvik,America/Iqaluit,America/Jamaica,America/Juneau,America/Kentucky/Louisville,America/Kentucky/Monticello,America/La_Paz,America/Lima,America/Los_Angeles,America/Maceio,America/Managua,America/Manaus,America/Marigot,America/Martinique,America/Mazatlan,America/Menominee,America/Merida,America/Mexico_City,America/Miquelon,America/Moncton,America/Monterrey,America/Montevideo,America/Montreal,America/Montserrat,America/Nassau,America/New_York,America/Nipigon,America/Nome,America/Noronha,America/North_Dakota/Center,America/North_Dakota/New_Salem,America/Panama,America/Pangnirtung,America/Paramaribo,America/Phoenix,America/Port-au-Prince,America/Port_of_Spain,America/Porto_Velho,America/Puerto_Rico,America/Rainy_River,America/Rankin_Inlet,America/Recife,America/Regina,America/Resolute,America/Rio_Branco,America/Santarem,America/Santiago,America/Santo_Domingo,America/Sao_Paulo,America/Scoresbysund,America/Shiprock,America/St_Barthelemy,America/St_Johns,America/St_Kitts,America/St_Lucia,America/St_Thomas,America/St_Vincent,America/Swift_Current,America/Tegucigalpa,America/Thule,America/Thunder_Bay,America/Tijuana,America/Toronto,America/Tortola,America/Vancouver,America/Whitehorse,America/Winnipeg,America/Yakutat,America/Yellowknife,Antarctica/Casey,Antarctica/Davis,Antarctica/DumontDUrville,Antarctica/Mawson,Antarctica/McMurdo,Antarctica/Palmer,Antarctica/Rothera,Antarctica/South_Pole,Antarctica/Syowa,Antarctica/Vostok,Arctic/Longyearbyen,Asia/Aden,Asia/Almaty,Asia/Amman,Asia/Anadyr,Asia/Aqtau,Asia/Aqtobe,Asia/Ashgabat,Asia/Baghdad,Asia/Bahrain,Asia/Baku,Asia/Bangkok,Asia/Beirut,Asia/Bishkek,Asia/Brunei,Asia/Choibalsan,Asia/Chongqing,Asia/Colombo,Asia/Damascus,Asia/Dhaka,Asia/Dili,Asia/Dubai,Asia/Dushanbe,Asia/Gaza,Asia/Harbin,Asia/Ho_Chi_Minh,Asia/Hong_Kong,Asia/Hovd,Asia/Irkutsk,Asia/Jakarta,Asia/Jayapura,Asia/Jerusalem,Asia/Kabul,Asia/Kamchatka,Asia/Karachi,Asia/Kashgar,Asia/Kathmandu,Asia/Kolkata,Asia/Krasnoyarsk,Asia/Kuala_Lumpur,Asia/Kuching,Asia/Kuwait,Asia/Macau,Asia/Magadan,Asia/Makassar,Asia/Manila,Asia/Muscat,Asia/Nicosia,Asia/Novosibirsk,Asia/Omsk,Asia/Oral,Asia/Phnom_Penh,Asia/Pontianak,Asia/Pyongyang,Asia/Qatar,Asia/Qyzylorda,Asia/Rangoon,Asia/Riyadh,Asia/Sakhalin,Asia/Samarkand,Asia/Seoul,Asia/Shanghai,Asia/Singapore,Asia/Taipei,Asia/Tashkent,Asia/Tbilisi,Asia/Tehran,Asia/Thimphu,Asia/Tokyo,Asia/Ulaanbaatar,Asia/Urumqi,Asia/Vientiane,Asia/Vladivostok,Asia/Yakutsk,Asia/Yekaterinburg,Asia/Yerevan,Atlantic/Azores,Atlantic/Bermuda,Atlantic/Canary,Atlantic/Cape_Verde,Atlantic/Faroe,Atlantic/Madeira,Atlantic/Reykjavik,Atlantic/South_Georgia,Atlantic/St_Helena,Atlantic/Stanley,Australia/Adelaide,Australia/Brisbane,Australia/Broken_Hill,Australia/Currie,Australia/Darwin,Australia/Eucla,Australia/Hobart,Australia/Lindeman,Australia/Lord_Howe,Australia/Melbourne,Australia/Perth,Australia/Sydney,Europe/Amsterdam,Europe/Andorra,Europe/Athens,Europe/Belgrade,Europe/Berlin,Europe/Bratislava,Europe/Brussels,Europe/Bucharest,Europe/Budapest,Europe/Chisinau,Europe/Copenhagen,Europe/Dublin,Europe/Gibraltar,Europe/Guernsey,Europe/Helsinki,Europe/Isle_of_Man,Europe/Istanbul,Europe/Jersey,Europe/Kaliningrad,Europe/Kiev,Europe/Lisbon,Europe/Ljubljana,Europe/London,Europe/Luxembourg,Europe/Madrid,Europe/Malta,Europe/Mariehamn,Europe/Minsk,Europe/Monaco,Europe/Moscow,Europe/Oslo,Europe/Paris,Europe/Podgorica,Europe/Prague,Europe/Riga,Europe/Rome,Europe/Samara,Europe/San_Marino,Europe/Sarajevo,Europe/Simferopol,Europe/Skopje,Europe/Sofia,Europe/Stockholm,Europe/Tallinn,Europe/Tirane,Europe/Uzhgorod,Europe/Vaduz,Europe/Vatican,Europe/Vienna,Europe/Vilnius,Europe/Volgograd,Europe/Warsaw,Europe/Zagreb,Europe/Zaporozhye,Europe/Zurich,Indian/Antananarivo,Indian/Chagos,Indian/Christmas,Indian/Cocos,Indian/Comoro,Indian/Kerguelen,Indian/Mahe,Indian/Maldives,Indian/Mauritius,Indian/Mayotte,Indian/Reunion,Pacific/Apia,Pacific/Auckland,Pacific/Chatham,Pacific/Easter,Pacific/Efate,Pacific/Enderbury,Pacific/Fakaofo,Pacific/Fiji,Pacific/Funafuti,Pacific/Galapagos,Pacific/Gambier,Pacific/Guadalcanal,Pacific/Guam,Pacific/Honolulu,Pacific/Johnston,Pacific/Kiritimati,Pacific/Kosrae,Pacific/Kwajalein,Pacific/Majuro,Pacific/Marquesas,Pacific/Midway,Pacific/Nauru,Pacific/Niue,Pacific/Norfolk,Pacific/Noumea,Pacific/Pago_Pago,Pacific/Palau,Pacific/Pitcairn,Pacific/Ponape,Pacific/Port_Moresby,Pacific/Rarotonga,Pacific/Saipan,Pacific/Tahiti,Pacific/Tarawa,Pacific/Tongatapu,Pacific/Truk,Pacific/Wake,Pacific/Wallis",
               "persistent": true
            },
            {
               "type": "string",
               "default": "pool.ntp.org",
               "label": "NTP server",
               "id": "ntp_server",
               "writable": true,
               "persistent": "true",
               "fn_set": null
            },
            {
               "type": "string",
               "default": "",
               "label": "NTP status",
               "id": "ntp_status",
               "writable": false,
               "persistent": "false"
            }
         ],
         "uid": "system clock",
         "type": "clock"
      },
      {
         "driver": "alert-log",
         "name": "-",
         "oid": "20fa6711",
         "propsval": {},
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "label": "Enable",
               "id": "enable",
               "writable": true,
               "persistent": true
            }
         ],
         "uid": "log alerts",
         "type": "alert"
      },
      {
         "driver": "smartbridge-uart",
         "name": "-",
         "oid": "36c1fc52",
         "propsval": [
            {
               "id": "available",
               "value": true
            },
            {
               "id": "metertype",
               "value": "Smart P1 DSMR 4"
            },
            {
               "id": "bytes_rx",
               "value": 1085038714
            },
            {
               "id": "bytes_tx",
               "value": 0
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "default": false,
               "label": "Available",
               "id": "available",
               "writable": false
            },
            {
               "fn_set": null,
               "type": "enum",
               "default": "-",
               "label": "Metertype",
               "id": "metertype",
               "writable": true,
               "range": "-,Smart P1,Smart P1 DSMR 4,IEC,analog,demo,modbus,gas only,dummy",
               "persistent": true
            },
            {
               "id": "bytes_rx",
               "type": "number",
               "writable": false,
               "label": "Bytes received"
            },
            {
               "id": "bytes_tx",
               "type": "number",
               "writable": false,
               "label": "Bytes transmitted"
            },
            {
               "type": "command",
               "label": "Firmware",
               "id": "fw-upgrade",
               "writable": true,
               "range": "upgrade",
               "fn_set": null
            },
            {
               "id": "message",
               "type": "string",
               "writable": false,
               "label": "message"
            }
         ],
         "uid": "/dev/ttyAPP:9600:e71",
         "type": "bridge"
      },
      {
         "driver": "users",
         "name": "-",
         "oid": "ebbe39cd",
         "propsval": [
            {
               "id": "blockuset",
               "value": false
            },
            {
               "id": "authenticated",
               "value": false
            },
            {
               "id": "language",
               "value": "nl"
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "password",
               "label": "password",
               "id": "password",
               "writable": true,
               "persistent": true,
               "fn_set": null
            },
            {
               "type": "boolean",
               "default": false,
               "label": "block user set",
               "id": "blockuset",
               "writable": true,
               "persistent": true
            },
            {
               "id": "authenticated",
               "type": "boolean",
               "default": false,
               "label": "authenticated"
            },
            {
               "type": "enum",
               "default": "nl",
               "label": "language",
               "id": "language",
               "writable": true,
               "range": "nl,en,de",
               "persistent": true
            },
            {
               "type": "string",
               "label": "settings",
               "id": "settings",
               "writable": true,
               "persistent": "true"
            }
         ],
         "uid": "admin",
         "type": "users"
      },
      {
         "driver": "alert-email",
         "name": "-",
         "oid": "b4286b84",
         "propsval": [
            {
               "id": "smtps",
               "value": false
            },
            {
               "id": "auth",
               "value": false
            },
            {
               "id": "from",
               "value": "alert@iungo.nl"
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "label": "Enable",
               "id": "enable",
               "writable": true,
               "persistent": true
            },
            {
               "type": "string",
               "label": "SMTP server",
               "id": "server",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "default": false,
               "label": "Use SMTPS protocol",
               "id": "smtps",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "default": false,
               "label": "Use authentication",
               "id": "auth",
               "writable": true,
               "persistent": true
            },
            {
               "type": "string",
               "label": "SMTP username",
               "id": "username",
               "writable": true,
               "persistent": true
            },
            {
               "type": "password",
               "label": "SMTP password",
               "id": "password",
               "writable": true,
               "persistent": true
            },
            {
               "type": "string",
               "default": "alert@iungo.nl",
               "label": "From address",
               "id": "from",
               "writable": true,
               "persistent": true
            },
            {
               "type": "string",
               "label": "Recipient address",
               "id": "rcpt",
               "writable": true,
               "persistent": true
            },
            {
               "type": "command",
               "label": "Send test e-mail",
               "id": "test",
               "writable": true,
               "range": "test",
               "fn_set": null
            },
            {
               "id": "status",
               "type": "string",
               "label": "Status"
            }
         ],
         "uid": "e-mail alerts",
         "type": "alert"
      },
      {
         "driver": "bridge-gpio",
         "name": "-",
         "oid": "b7bae611",
         "propsval": [
            {
               "id": "available",
               "value": false
            },
            {
               "id": "pulses_rx",
               "value": 0
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "default": false,
               "label": "Available",
               "id": "available",
               "writable": false
            },
            {
               "id": "pulses_rx",
               "type": "number",
               "writable": false,
               "label": "Pulses received"
            }
         ],
         "uid": "39",
         "type": "bridge"
      },
      {
         "driver": "bridge-modbus",
         "name": "-",
         "oid": "b9cb127f",
         "propsval": {},
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "id": "rawmsg",
               "type": "string",
               "writable": "true",
               "label": "raw msg"
            },
            {
               "type": "command",
               "label": "send raw",
               "id": "rawsend",
               "range": "send",
               "fn_set": null
            }
         ],
         "uid": "via 1-1.2:1.0",
         "type": "bridge"
      },
      {
         "driver": "energy-dsmr4",
         "name": "Energiemeters",
         "oid": "538d72d9",
         "propsval": [
            {
               "id": "name",
               "value": "Energiemeters"
            },
            {
               "id": "metertype",
               "value": "Ene"
            },
            {
               "id": "version",
               "value": "5"
            },
            {
               "id": "serial_e",
               "value": "4530303438303030303333373636353139"
            },
            {
               "id": "usage",
               "value": 356
            },
            {
               "id": "T1",
               "value": 531.433
            },
            {
               "id": "T2",
               "value": 273.206
            },
            {
               "id": "-T1",
               "value": 0.098
            },
            {
               "id": "-T2",
               "value": 0
            },
            {
               "id": "L1I",
               "value": 0
            },
            {
               "id": "L2I",
               "value": 0
            },
            {
               "id": "L3I",
               "value": 0
            },
            {
               "id": "L1Pimp",
               "value": 0.19260606060606
            },
            {
               "id": "L2Pimp",
               "value": 0.1599696969697
            },
            {
               "id": "L3Pimp",
               "value": 0
            },
            {
               "id": "L1Pexp",
               "value": 0
            },
            {
               "id": "L2Pexp",
               "value": 0
            },
            {
               "id": "L3Pexp",
               "value": 0
            },
            {
               "id": "c_tariff",
               "value": 2
            },
            {
               "id": "serial_g",
               "value": "4730303539303033373931353830383138"
            },
            {
               "id": "gas_usage",
               "value": 0
            },
            {
               "id": "gas",
               "value": 663.883
            },
            {
               "id": "Cost-T1",
               "value": 0.22074
            },
            {
               "id": "Cost-T2",
               "value": 0.23284
            },
            {
               "id": "Cost-nT1",
               "value": 0
            },
            {
               "id": "Cost-nT2",
               "value": 0
            },
            {
               "id": "Cost-gas",
               "value": 0.77298
            },
            {
               "id": "Gas-interval",
               "value": 300
            },
            {
               "id": "Client-blob",
               "value": ""
            },
            {
               "id": "available",
               "value": true
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "string",
               "label": "Energy provider",
               "id": "provider_e",
               "writable": true,
               "persistent": true
            },
            {
               "id": "metertype",
               "type": "string",
               "label": "type"
            },
            {
               "id": "version",
               "type": "string",
               "label": "SMR"
            },
            {
               "type": "string",
               "label": "E meter sn",
               "id": "serial_e",
               "persistent": true,
               "logchange": true
            },
            {
               "type": "number",
               "label": "Energy usage",
               "id": "usage",
               "log": true,
               "unit": "Watt"
            },
            {
               "type": "number",
               "label": "T1",
               "id": "T1",
               "log": true,
               "cumulative": true,
               "unit": "kWh"
            },
            {
               "type": "number",
               "label": "T2",
               "id": "T2",
               "log": true,
               "cumulative": true,
               "unit": "kWh"
            },
            {
               "type": "number",
               "label": "-T1",
               "id": "-T1",
               "log": true,
               "cumulative": true,
               "unit": "kWh"
            },
            {
               "type": "number",
               "label": "-T2",
               "id": "-T2",
               "log": true,
               "cumulative": true,
               "unit": "kWh"
            },
            {
               "type": "number",
               "label": "L1 Current",
               "id": "L1I",
               "log": true,
               "unit": "Amp"
            },
            {
               "type": "number",
               "label": "L2 Current",
               "id": "L2I",
               "log": true,
               "unit": "Amp"
            },
            {
               "type": "number",
               "label": "L3 Current",
               "id": "L3I",
               "log": true,
               "unit": "Amp"
            },
            {
               "type": "number",
               "label": "L1 Power Import",
               "id": "L1Pimp",
               "log": true,
               "unit": "kW"
            },
            {
               "type": "number",
               "label": "L2 Power Import",
               "id": "L2Pimp",
               "log": true,
               "unit": "kW"
            },
            {
               "type": "number",
               "label": "L3 Power Import",
               "id": "L3Pimp",
               "log": true,
               "unit": "kW"
            },
            {
               "type": "number",
               "label": "L1 Power Export",
               "id": "L1Pexp",
               "log": true,
               "unit": "kW"
            },
            {
               "type": "number",
               "label": "L2 Power Export",
               "id": "L2Pexp",
               "log": true,
               "unit": "kW"
            },
            {
               "type": "number",
               "label": "L3 Power Export",
               "id": "L3Pexp",
               "log": true,
               "unit": "kW"
            },
            {
               "type": "number",
               "label": "Tariff",
               "id": "c_tariff",
               "log": true,
               "unit": "x"
            },
            {
               "type": "string",
               "label": "Gas meter sn",
               "id": "serial_g",
               "persistent": true,
               "logchange": true
            },
            {
               "type": "string",
               "label": "Gas provider",
               "id": "provider_g",
               "writable": true,
               "persistent": true
            },
            {
               "type": "number",
               "label": "Gas usage",
               "id": "gas_usage",
               "log": true,
               "unit": "m³"
            },
            {
               "type": "number",
               "label": "Gas total",
               "id": "gas",
               "log": true,
               "cumulative": true,
               "unit": "m³"
            },
            {
               "log": true,
               "type": "number",
               "default": 0,
               "label": "€ T1",
               "id": "Cost-T1",
               "writable": true,
               "persistent": true,
               "unit": "¤/kWh"
            },
            {
               "log": true,
               "type": "number",
               "default": 0,
               "label": "€ T2",
               "id": "Cost-T2",
               "writable": true,
               "persistent": true,
               "unit": "¤/kWh"
            },
            {
               "log": true,
               "type": "number",
               "default": 0,
               "label": "€ -T1",
               "id": "Cost-nT1",
               "writable": true,
               "persistent": true,
               "unit": "¤/kWh"
            },
            {
               "log": true,
               "type": "number",
               "default": 0,
               "label": "€ -T2",
               "id": "Cost-nT2",
               "writable": true,
               "persistent": true,
               "unit": "¤/kWh"
            },
            {
               "log": true,
               "type": "number",
               "default": 0,
               "label": "€ Gas",
               "id": "Cost-gas",
               "writable": true,
               "persistent": true,
               "unit": "¤/m3"
            },
            {
               "type": "number",
               "default": 3600,
               "label": "Gas interval",
               "id": "Gas-interval",
               "persistent": true,
               "unit": "sec"
            },
            {
               "type": "string",
               "default": "",
               "label": "Client-blob",
               "id": "Client-blob",
               "writable": true,
               "persistent": true,
               "hidden": true
            },
            {
               "id": "available",
               "type": "boolean",
               "label": "Available"
            }
         ],
         "uid": "-",
         "type": "energy"
      },
      {
         "driver": "energymeter-sdm630-modbus",
         "name": "Tesla Wall Connector",
         "oid": "64904b93",
         "propsval": [
            {
               "id": "name",
               "value": "Tesla Wall Connector"
            },
            {
               "id": "usage",
               "value": 0
            },
            {
               "id": "T1",
               "value": 441.25198364258
            },
            {
               "id": "-T1",
               "value": 0
            },
            {
               "id": "Cost-T1",
               "value": 0
            },
            {
               "id": "Cost-nT1",
               "value": 0
            },
            {
               "id": "functiongroup",
               "value": "carcharger"
            },
            {
               "id": "Client-blob",
               "value": ""
            },
            {
               "id": "hidden",
               "value": false
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "number",
               "label": "Power",
               "id": "usage",
               "log": true,
               "unit": "Watt"
            },
            {
               "type": "number",
               "label": "T1",
               "id": "T1",
               "log": true,
               "cumulative": true,
               "unit": "kWh"
            },
            {
               "type": "number",
               "label": "-T1",
               "id": "-T1",
               "log": true,
               "cumulative": true,
               "unit": "kWh"
            },
            {
               "log": true,
               "type": "number",
               "default": 0,
               "label": "€ T1",
               "id": "Cost-T1",
               "writable": true,
               "persistent": true,
               "unit": "¤/kWh"
            },
            {
               "log": true,
               "type": "number",
               "default": 0,
               "label": "€ -T1",
               "id": "Cost-nT1",
               "writable": true,
               "persistent": true,
               "unit": "¤/kWh"
            },
            {
               "type": "enum",
               "default": "misc",
               "label": "Functiongroup",
               "id": "functiongroup",
               "writable": true,
               "range": "misc,carcharger,heatpump,device,waterboiler,floorheating,airco,oven,stove,fridge,dishwasher,heating,ventilation,aux,ehelp,laundryroom,carwash,irpanel,groupByName",
               "persistent": true
            },
            {
               "type": "string",
               "default": "",
               "label": "Client-blob",
               "id": "Client-blob",
               "writable": true,
               "persistent": true,
               "hidden": true
            },
            {
               "type": "boolean",
               "default": false,
               "label": "Hidden",
               "id": "hidden",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "label": "Available",
               "id": "available",
               "writable": false,
               "log": false
            }
         ],
         "uid": "2",
         "type": "modbusenergy"
      },
      {
         "driver": "bridge-usbuart",
         "name": "-",
         "oid": "0cbea738",
         "propsval": [
            {
               "id": "available",
               "value": false
            }
         ],
         "propertyInfo": [
            {
               "type": "string",
               "label": "Name",
               "id": "name",
               "writable": true,
               "persistent": true
            },
            {
               "type": "boolean",
               "default": false,
               "label": "Available",
               "id": "available",
               "writable": false
            }
         ],
         "uid": "1-1.2:1.0;9600",
         "type": "bridge"
      }
   ],
   "version": {
      "revision": "3439",
      "time": "14:27:07",
      "date": "Jun 28 2019",
      "serial": "37E1"
   }
}

Verder nog wat screenshots. Als je nog meer info nodig hebt dan hoor ik het graag!

Alvast bedankt

Erik
![2019-07-16 20_39_30-Window](https://user-images.githubusercontent.com/42382514/61320615-0778b000-a80a-11e9-9f6b-a4c37bfc2313.png)

**Comment by robertraaijmakers** [comment]
Heb een mogelijk fix doorgevoerd en aan Athom aangeboden als beta approval. Je zult straks wel het device opnieuw moeten registeren als "Energie Meter". Ik denk dat er namelijk een fout zat bij het toevoegen van de capabilities. Hij ging er vanuit dat er altijd gas waarden in de energie meter zouden zitten en dat is natuurlijk niet het geval.

Zal binnenkort beta 0.3.4 pushen als Athom hem goedgekeurd heeft, dan kan je deze testen (aangezien ik dat zelf helaas niet kan).

**Comment by robertraaijmakers** [comment]
Zojuist 0.3.4 beta uitgerold. Als je de beta installeert en je device opnieuw registreert zou hij het moeten doen. Kan je dit testen en bevestigen?

**Comment by ezwep** [comment]
Hoi Robert

Bedankt voor de update. Ik heb de nieuwe versie getest maar hij werkt helaas nog niet. Ik heb voor de zekerheid de app eerst helemaal verwijderd en opnieuw geïnstalleerd.

Mvg Erik

Met vriendelijke groet,

________________________________
Van: Robert <notifications@github.com>
Verzonden: donderdag, juli 25, 2019 1:58 PM
Aan: robertraaijmakers/com.iungo
CC: ezwep; Author
Onderwerp: Re: [robertraaijmakers/com.iungo] modbus usb stick niet beschikbaar (#10)


Zojuist 0.3.4 beta uitgerold. Als je de beta installeert en je device opnieuw registreert zou hij het moeten doen. Kan je dit testen en bevestigen?

**Comment by robertraaijmakers** [comment]
Hi Erik,

Dat is jammer. Crasht de app? 
Zou je via een diagnostics report kunnen sturen. Dit kan via: 
More --> Apps --> Trashcan Reminder 2.0 --> Settings (rechts bovenin) --> Create Diagnostics Report --> (vul wat random tekst in)  --> Send Report

Misschien dat ik daar nog wat uit af kan leiden.

Thanks!

**Comment by ezwep** [comment]
2081e320-2862-4188-93df-f01813176b8f

Met vriendelijke groet,
________________________________

**Comment by robertraaijmakers** [comment]
Thanks, heb één aanpassing gedaan. Blijkbaar heeft de modbus geen 'present' tag (of een device aanwezig is) zoals alle andere apparaten. Maar de modbus werkt met een 'visible' tag. Heb dit dus omgebouwd.

Zag wel wat andere gekke promise errors nog binnenkomen in de log die je had gestuurd, maar hoop dat met bovenstaande aanpassing ook die errors niet meer voorkomen, maar heb sterke twijfels.

Heb nu in ieder geval een nieuwe beta versie aan de app store aangeboden en zal hem doorzetten op het moment dat hij goedgekeurd is.

**Comment by ezwep** [comment]
Bedankt. Het werkt nu!

Met vriendelijke groet,

________________________________
Van: Robert <notifications@github.com>
Verzonden: vrijdag, juli 26, 2019 3:53 PM
Aan: robertraaijmakers/com.iungo
CC: ezwep; Author
Onderwerp: Re: [robertraaijmakers/com.iungo] modbus usb stick niet beschikbaar (#10)


Thanks, heb één aanpassing gedaan. Blijkbaar heeft de modbus geen 'present' tag (of een device aanwezig is) zoals alle andere apparaten. Maar de modbus werkt met een 'visible' tag. Heb dit dus omgebouwd.

Zag wel wat andere gekke promise errors nog binnenkomen in de log die je had gestuurd, maar hoop dat met bovenstaande aanpassing ook die errors niet meer voorkomen, maar heb sterke twijfels.

Heb nu in ieder geval een nieuwe beta versie aan de app store aangeboden en zal hem doorzetten op het moment dat hij goedgekeurd is.

**Comment by robertraaijmakers** [comment]
Cool! Goed om te horen.
