### ISSUE TITLE
Lost connection since homey v6 

### ISSUE THREAD

**Issue by friso74** [robertraaijmakers/com.iungo#17]
Since the update of my homey to version V6, no iungo data is received by homey. Restart of app not successful. Tried to remove and reinstall iungo device, but unable find. After removingand reinstallation of app, similar result. 
please advice

**Comment by robertraaijmakers** [comment]
Hi there, have you tried rebooting the Iungo itself and after an Iungo reboot, then reboot Homey?

**Comment by friso74** [comment]
Rebooting homey was the solution. Didn’t try rebooting iungo first.
