### ISSUE TITLE
Cannot connect to my Iungo Energy Controller

### ISSUE THREAD

**Issue by djvanharten** [robertraaijmakers/com.iungo#18]
I try to connect my iungo energy controller to my Homey. Homey app comes with message "Selecteer de juiste Iungo Controller" the only choice I have is IUNGOBOX. I click next, than the message 'Could not find that PairSession' or 'Er zijn geen nieuwe apparaten gevonden'

**Comment by ghost** [comment]
I have the same issue. How to solve?

**Comment by djvanharten** [comment]
If you have the same problem when using the iungo app, the problem has to do with the network connection of your iungo. This was the case in my situation, because I was running on a network running on a 4G connection.
After changing to the fiber connection the prblem was solved.

**Comment by ghost** [comment]
Tnx for your reply!
Indeed, has to do with my vlans!

**Comment by robertraaijmakers** [comment]
Does this mean this issue is resolved?

**Comment by ghost** [comment]
Yes. Apparently there was no issue.
I forgot I connected my iungo to a different vlan than my homey... hence it was not possible to connect...
