### ISSUE TITLE
Connection has been lost for 24 days and no new devices are found when reconnecting.

### ISSUE THREAD

**Issue by ezwep** [robertraaijmakers/com.iungo#19]
I just found out that Homey has been disconnected from my iungo controller for 24 days. I then tried everything to restore this connection but without success:
- Firmware iungo updated
- Restart iungo controller
- Device and app re-added on Homey
- Homey restart
If I want to add the iungo again from the app, it will find the controller, but then I get the message: no new devices were found.

How can I solve this?

**Comment by ezwep** [comment]
I did some more checking to see what has changed on my network since the problem started. Around that time I changed internet provider. I've checked all the settings in my router and wifi but I can't find anything strange. I can just browse the web interface from my PC.
Is there anyone who can help me with this?

**Comment by robertraaijmakers** [comment]
Hi Erik,

Wat vervelend om te horen dat de verbinding het al ruimere tijd niet meer doet en het lijkt er ook op dat je al vele stappen hebt ondernomen om hem weer aan de praat te krijgen.

Wat je kan doen (vanaf je eigen lokale netwerk) eens naar deze site gaan: http://www.atedec.com/iungo/myiungoip . Als het goed is krijg je daar dan vervolgens de lokale IP te zien waar je Iungo op draait. In principe verwacht ik dat dit gewoon werkt, aangezien hij wel de Iungo lijkt te vinden, maar vervolgens niet je devices.

Verder zie ik nog een aantal debug opties die mogelijk kunnen werken:
1. Verwijder de devices uit je Homey;
2. Restart je Homey;
3. Probeer de devices vervolgens toe te voegen.

Als dat niet werkt dan wordt het iets lastiger (wat meer werk om te herstellen):
1. Verwijder de devices;
2. Verwijder de Iungo app;
3. Restart je Homey;
4. Installeer de app;
5. Voeg je devices weer toe.

Als beide stappenplannen niet werken dan wordt het voor mij op dit moment lastig debuggen. Aangezien ik zelf geen beschikking meer heb over Homey (op dit moment) en ook niet meer over de Iungo. Hopelijk komt dat allemaal rond november dit jaar, maar dat duurt nog even ;) dus laten we hopen dat één van de twee bovenstaande stappenplannen werken.

Met vriendelijke groet,
Robert

**Comment by ezwep** [comment]
Hoi Robert,

Bedankt voor je reactie.
Als ik naar  http://www.atedec.com/iungo/myiungoip ga dan krijg ik een
ander IP (192.168.178.22) te zien dan waar mijn iungo op bereikbaar is
(192.168.178.10). Op .22 zit een ander apparaat en op .10 kan ik de Iungo
bereiken.

Is er een manier om het IP te wijzigen o.i.d.?

m.v.g Erik


Op zo 27 feb. 2022 om 20:17 schreef Robert ***@***.***>:

**Comment by robertraaijmakers** [comment]
Hm, dat verklaart wel waarom hij het niet doet dan!
Wel gek dat hij dit niet bijwerkt, in principe pingt je Iungo 1 keer per dag de server bij Iungo om te laten weten waar hij op draait. Dit wordt tevens ook gebruikt in de app van Iungo zelf om hem te zoeken....

Er zijn 2 opties:
1. Je kan zorgen dat je firewall de uitgaande verbinding van je Iungo accepteert en dat je Iungo zo de server van Iungo bij kan laten werken met het juiste intere IP-adres
2. Je kan je Iungo een vast IP geven (dit moet meestal in je router gebeuren). Echter dit is heel merk afhankelijk hoe dit geregeld is. En in dit geval zou hij dan het vaste interne IP eindigend op .22 moeten krijgen (en daarvoor moet je dat andere apparaat eerst eraf gooien.

**Comment by ezwep** [comment]
Hoi Robert,

Bedankt voor je reacties. Hier kan ik in ieder geval weer verder mee.
Ik vermoed dat mijn internet provider iets blokkeert, maar dat gaan we eens
uitzoeken.

Bedankt voor je hulp zover!

m.v.g Erik


Op zo 27 feb. 2022 om 21:14 schreef Robert ***@***.***>:

**Comment by ezwep** [comment]
Hoi Robert,

Ik heb mijn ipreservering aangepast naar .22 en hierdoor werkt het.
Bedankt!

m.v.g Erik


Op ma 28 feb. 2022 om 09:07 schreef Erik Zwep ***@***.***>:

**Comment by robertraaijmakers** [comment]
Great to hear!

**Comment by ezwep** [comment]
Hoi Robert,

We zijn nu een paar maand verder en ik heb contact gehad met Iungo en met
mijn internet provider (kliksafe). Uiteindelijk hebben we het aan de praat
gekregen. Mijn internet provider maakt gebruik van een Proxy/ filter
platform, en ze hebben het ip wat hoort bij atedec.com gewhitelisted.
Daarna werkte het. Op 1 of andere manier gaat daar iets mis, of geven ze
aan, communiceert het apparaat niet volgens de standaarden waardoor het
geblokkeerd wordt.

Verder heb ik gemerkt dat de helpdesk van Iungo eigenlijk heel verbaasd was
en ook niet bekend was met de werking van de Iungo box, dat deze verbinding
maakt met http://www.atedec.com/iungo/myiungo om daar het lokale IP te
registreren, alleen de ontwikkelaar wist hiervan af. Maar goed, het werkt
nu.
Ik weet niet of je ooit het nog anders kunt programmeren zodat de Homey
niet afhankelijk van de externe website:
http://www.atedec.com/iungo/myiungoip om te verbinden met het Iungo
apparaat, je merkt dat je afhankelijk hiervan bent. Misschien een optie dat
je zelf het lokale IP van de Iungo kunt ingeven, dan is het ook klaar.

Nogmaals bedankt voor jouw hulp.

m.v.g Erik


Op zo 27 feb. 2022 om 21:14 schreef Robert ***@***.***>:

**Comment by robertraaijmakers** [comment]
Bedankt voor de terugkoppeling!

Iungo is een tweemans bedrijf (1 ontwikkelaar en zijn partner), althans, dat waren ze toen ik de app ooit maakte een aantal jaar geleden. Toen was dit de enige manier om het IP adres te achterhalen (heb dat toen met Iungo besproken).

Heb toentertijd ook gekeken of mensen zelf een IP op konden geven, alleen was het toen in de wizard mogelijkheden van Homey niet mogelijk om een alternatief te kiezen. Daar laat Homey niet heel veel ruimte, althans, toen niet. Heb al een tijdje niet meer naar de ontwikkel(on)mogelijkheden van de Homey en het koppelen van devices gekeken. Misschien dat dit inmiddels wel een stuk verbetert is.
