### ISSUE TITLE
Homey has lost my Iungo

### ISSUE THREAD

**Issue by Beez55** [robertraaijmakers/com.iungo#22]
Already a few months ago Homey lost my Iungo. I have more than once uninstalled your app, reinstalled, but always with the same not so positive result as shown in attached screen grabs:
![IMG_6800](https://user-images.githubusercontent.com/106333584/170521549-c612e86a-c9ac-4453-b2a9-8c74e376dd4f.PNG)
![IMG_6801](https://user-images.githubusercontent.com/106333584/170521563-87402608-e780-4b97-a65c-edee61057487.PNG)
.
Any suggestions for a solution?

**Comment by robertraaijmakers** [comment]
Hi Bart,

dit lijkt vaker te gebeuren. Kan je eens proberen de instructies uit issue #19 te volgen? https://github.com/robertraaijmakers/com.iungo/issues/19

**Comment by Beez55** [comment]
Hi Robert, dank voor je reactie. Blijkbaar is de issue bij mij toch een andere: mijn Iungo stond al op een vast adres (192.168.2.16) dat ook door de site werd bevestigd. De tweede set (uitgebreidere) herstelstappen heb ik nog maar eens gedaan, maar zonder resultaat. Ik hoop dat er een oplossing komt als jij in november hier weer aan toe komt.

**Comment by robertraaijmakers** [comment]
Dat is inderdaad wel irritant als hij hem niet meer lijkt mee te pakken dan. Wat vroeger nog wel eens hielp was deïnstalleren en vervolgens de Homey herstarten. Dit wist de devices namelijk pas echt en als het goed is ook de app cache. Maar weet niet hoe dat tegenwoordig is. Ook grote kans dat er iets is omgevallen in de tussentijd met de Homey updates omdat ze inmiddels 6 NodeJS versies verder zijn en dit toch wel vrij grote impact heeft op sommige zaken. Zal dit zeker in november gaan oppakken, dan kan ik alles ook weer goed doortesten

**Comment by robertraaijmakers** [comment]
Mogelijk gerelateerd aan #24

**Comment by robertraaijmakers** [comment]
Beste @BartBeers, welk apparaat probeert u toe te voegen?

<img width="293" alt="image" src="https://user-images.githubusercontent.com/1773099/218243637-9065ce80-2f14-479f-94d7-a0de1f3b8130.png">

**Comment by robertraaijmakers** [comment]
En daarop volgend, zou je onderstaand request kunnen uitvoeren (in Chrome)?

1. Open de developer tools (F12 als je in Chrome zit)
2. Open het tabje "Console"
3. Plak daar het volgende stuk code en verander op de eerste regel het IP adres naar het IP-adres van je Iungo (deze kan je vinden door te browsen naar: http://www.atedec.com/iungo/myiungoip)
```
fetch('http://192.168.178.13/iungo/api_request', {
  method: 'POST',
  body: JSON.stringify({
    seq: 1,
    method: 'objmgr_get_objects_init',
    arguments: []
  }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log)
```
4. Het resultaat daarvan te delen hier

**Comment by Beez55** [comment]
Hallo Robert,

MIjn Iungo Energy Meter wordt nu wel weer gevonden en werkt zoals tevoren.
Gelijk (?) hiermee worden nu ook weer de Philips Hue hub en de Enphase
Envoy gevonden.
Het probleem lijkt dus hier opgelost.

Groet,
Bart

Op za 11 feb. 2023 om 07:45 schreef Robert ***@***.***>:
