### ISSUE TITLE
Melding geen nieuwe apparaten gevonden

### ISSUE THREAD

**Issue by Olaf1979** [robertraaijmakers/com.iungo#24]
Ik heb de iungo app verwijderd en opnieuw geïnstalleerd. Ik krijg nu bij elk apparaat de melding geen nieuwe apparaten gevonden. Hij vindt wel de iungo box

**Comment by robertraaijmakers** [comment]
Het beste kan je de app verwijderen. Homey uitzetten. Vervolgens Homey weer opstarten en daarna de app weer installeren. Pas bij het uit- en weer aanzetten van de Homey wist hij zijn 'cache' aan (verwijderde) devices.

**Comment by Olaf1979** [comment]
> Het beste kan je de app verwijderen. Homey uitzetten. Vervolgens Homey weer opstarten en daarna de app weer installeren. Pas bij het uit- en weer aanzetten van de Homey wist hij zijn 'cache' aan (verwijderde) devices.

Ik heb dit gedaan maar nog steeds zelfe resultaat. Hij vindt wel de iungobox naar vervolgens geen nieuwe apparaten gevonden.

**Comment by robertraaijmakers** [comment]
Beste, wat voor apparaat van de Iungo probeer je toe te voegen?

<img width="293" alt="image" src="https://user-images.githubusercontent.com/1773099/218243613-000994b2-e273-4887-91d3-2e31a9f63569.png">

**Comment by robertraaijmakers** [comment]
En daarop volgend, zou je onderstaand request kunnen uitvoeren in Chrome?

1. Open de developer tools (F12 als je in Chrome zit)
2. Open het tabje "Console"
3. Plak daar het volgende stuk code en verander op de eerste regel het IP adres naar het IP-adres van je Iungo (deze kan je vinden door te browsen naar: http://www.atedec.com/iungo/myiungoip)
```
fetch('http://192.168.178.13/iungo/api_request', {
  method: 'POST',
  body: JSON.stringify({
    seq: 1,
    method: 'objmgr_get_objects_init',
    arguments: []
  }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log)
```
4. Het resultaat daarvan te delen hier

**Comment by Olaf1979** [comment]
> Beste, wat voor apparaat van de Iungo probeer je toe te voegen?
> 
> <img alt="image" width="293" src="https://user-images.githubusercontent.com/1773099/218243613-000994b2-e273-4887-91d3-2e31a9f63569.png">

Ik probeer een energy meter en watermeter te installeren.

**Comment by Olaf1979** [comment]
> En daarop volgend, zou je onderstaand request kunnen uitvoeren in Chrome?
> 
> 1. Open de developer tools (F12 als je in Chrome zit)
> 2. Open het tabje "Console"
> 3. Plak daar het volgende stuk code en verander op de eerste regel het IP adres naar het IP-adres van je Iungo (deze kan je vinden door te browsen naar: http://www.atedec.com/iungo/myiungoip)
> 
> ```
> fetch('http://192.168.178.13/iungo/api_request', {
>   method: 'POST',
>   body: JSON.stringify({
>     seq: 1,
>     method: 'objmgr_get_objects_init',
>     arguments: []
>   }),
>   headers: {
>     'Content-type': 'application/json; charset=UTF-8'
>   }
> })
> .then(res => res.json())
> .then(console.log)
> ```
> 
> 4. Het resultaat daarvan te delen hier

![iungo](https://user-images.githubusercontent.com/124811595/218259420-d6e4dcbf-1868-4777-8543-aa52897c32cc.JPG)

**Comment by robertraaijmakers** [comment]
Dit zou wel verklaren waarom er geen aparaten gevonden kunnen worden. Als dat het IP van je Iungo is en er geen response komt op dit request dan doet de Iungo het niet.

Welke firmware van Iungo draai je? Deze kan je vinden in de Iungo app
http://192.168.178.124/iungo/app/#/settings --> Firmware.

**Comment by Olaf1979** [comment]
> Dit zou wel verklaren waarom er geen aparaten gevonden kunnen worden. Als dat het IP van je Iungo is en er geen response komt op dit request dan doet de Iungo het niet.
> 
> Welke firmware van Iungo draai je? Deze kan je vinden in de Iungo app http://192.168.178.124/iungo/app/#/settings --> Firmware.

Hi. De iungo doet het gewoon en is op dat ip adres vanuit de browser en de smart phone gewoon te benaderen. Ook buiten de lan kan ik via iungoconnect.eu er gewoon bij. De firmware is 4299

**Comment by Olaf1979** [comment]
![Screenshot_20230213_100942_Chrome](https://user-images.githubusercontent.com/124811595/218417246-7f008612-14b3-4fdb-bcfc-4ef71d15ec44.png)

**Comment by robertraaijmakers** [comment]
Heel apart, ik heb het script even uitgebreid met een error regel, misschien dat er dan net wat meer informatie naar voren komt waarom hij de query niet uit kan voeren. Ik zie dat de firmware op dezelfde versie zit als bij mij, dus dat zou het verschil niet moeten zijn.


```
fetch('http://192.168.1.124/iungo/api_request', {
  method: 'POST',
  body: JSON.stringify({
    seq: 1,
    method: 'objmgr_get_objects_init',
    arguments: []
  }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8'
  }
})
.then(res => res.json())
.then(console.log)
.catch(console.log)
```

**Comment by robertraaijmakers** [comment]
Wat mogelijk nog kan zijn is dat er een username & wachtwoord op de API zit omdat je externe toegang open hebt staan... ik heb dit zelf uitstaan omdat ik via de Homey (die beter beveiligd is) de waarden uit kan lezen. De app kan niet omgaan met een username & password. Dus als de API inderdaad afgeschermd is via een username en password dan kan je de Homey app niet gebruiken.

**Comment by Olaf1979** [comment]
> fetch('http://192.168.1.124/iungo/api_request', {
>   method: 'POST',
>   body: JSON.stringify({
>     seq: 1,
>     method: 'objmgr_get_objects_init',
>     arguments: []
>   }),
>   headers: {
>     'Content-type': 'application/json; charset=UTF-8'
>   }
> })
> .then(res => res.json())
> .then(console.log)
> .catch(console.log)

Ik blijf fout melding krijg. Ik heb voorheen altijd de iungo app gebruikt en altijd externe toegang op de iungo aangehad. Ik heb homey moeten restarten vanwege een nieuwe power adapter die ik geinstalleerd heb. Daarna deed de homey iungo app het opeens niet meer.

**Comment by robertraaijmakers** [comment]
Nog steeds dezelfde fout ook of staan er wat meer details in?

Als hij het eerder wel gedaan heeft kan het niet zo zeer met de externe toegang te maken hebben. Het enige wat ik mij dan kan bedenken is dat het IP-adres van de Iungo veranderd is en dat dit zich niet (automatisch) hersteld in Homey waardoor de verbinding tussen de Homey en de Iungo niet meer werkt.

Maar ik blijf het wel apart vinden dat die fetch geen resultaat geeft. Dit lijkt eerder te duiden op een issue in de web API van de Iungo en dat daar iets corrupt is geraakt. Zolang dat request geen response geeft kan ik namelijk ook niks doen in de Iungo Homey app omdat ik de response van die web request gebruik. Zolang die er niet is, zullen er dus ook nooit devices gevonden worden.

Misschien een idee om een bericht op het Iungo form te plaatsen of contact op te nemen met Iungo support om te kijken waarom het niet lijkt te werken. Zij kunnen van afstand ook op je Iungo box kijken om te zien of ze iets geks zien.

**Comment by Olaf1979** [comment]
Beste Robert

Probleem is opgelost. Ik heb gisteren de iungo 10 minuten van de steoom gehaald en vervolgens weer verbonden. Nu werkt de homey iungo app weer. 
Bedankt voor het meedenken en de support!
