### ISSUE TITLE
Gas consumption

### ISSUE THREAD

**Issue by henkbart** [robertraaijmakers/com.iungo#27]
Hello,
First of all, thank you for this app.
I have a question.
Now this app shows the current consumption of energy (Electricity) in the tile.
Could you also make this for the current Gas consuption. Now i can only see the telwerk, but not the actual consumption.
Greetings,

Henk

**Comment by robertraaijmakers** [comment]
Hi Henk,

Sorry, gas consumption can't be read 'real-time'. The gas consumption (better said: gas meter value) is only passed to the P1 meter every hour and has no direct real-time link with the P1 meter. Therefor the Iungo box also can't read out this value.

With kind regards,
Robert
