### ISSUE TITLE
Water Meter

### ISSUE THREAD

**Issue by henkbart** [robertraaijmakers/com.iungo#28]
Hello,

I have a Watermeter connected to the Iungo via a Breakbox.
Is it possible to add this to your app.
A donation is given when you do so.

Thank you

Henk Bartels

**Comment by robertraaijmakers** [comment]
Hi @henkbart,

Het is voor mij erg lastig om te ontwikkelen voor Iungo aangezien het lastig is informatie te verkrijgen over devices die ik zelf niet in bezit heb. Is dit type device voor jou nog relevant? Zo ja, zou je dan de details kunnen delen die je terug krijgt bij deze URL: http://<< IP VAN JOUW IUNGO>>/iungo/api_request/objmgr_get_objects_init ?

**Comment by henkbart** [comment]
Hallo Robert,

Hierbij de JSON info.

{
     "ok": true,
     "type": "response",
     "time": 0.015094532631338,
     "rv": {
         "objects": [
             {
                 "driver": "bridge-zwave",
                 "name": "-",
                 "oid": "b8d4960b",
                 "propsval": [
                     {
                         "id": "home_id",
                         "value": 8771
                     },
                     {
                         "id": "available",
                         "value": false
                     },
                     {
                         "id": "node_count",
                         "value": 1
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "number",
                         "label": "home id",
                         "id": "home_id",
                         "writable": false,
                         "logchange": true
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Available",
                         "id": "available",
                         "writable": false
                     },
                     {
                         "type": "number",
                         "default": 0,
                         "label": "nodes",
                         "id": "node_count",
                         "writable": false
                     },
                     {
                         "type": "command",
                         "fn_set": null,
                         "label": "node",
                         "id": "operation",
                         "writable": true,
                         "range": "add,delete,reset",
                         "persistent": true
                     },
                     {
                         "id": "cmd",
                         "type": "string",
                         "writable": true,
                         "label": "cmd"
                     },
                     {
                         "type": "command",
                         "label": "exec",
                         "id": "exec",
                         "range": "exec",
                         "fn_set": null
                     },
                     {
                         "id": "message",
                         "type": "string",
                         "writable": false,
                         "label": "message"
                     }
                 ],
                 "uid": "via 1-1.3:1.1",
                 "type": "bridge"
             },
             {
                 "driver": "bridge-usbuart",
                 "name": "-",
                 "oid": "ce7985b3",
                 "propsval": [
                     {
                         "id": "available",
                         "value": false
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Available",
                         "id": "available",
                         "writable": false
                     }
                 ],
                 "uid": "1-1.3:1.1;115200",
                 "type": "bridge"
             },
             {
                 "driver": "bridge-zigbee",
                 "name": "-",
                 "oid": "fb979233",
                 "propsval": [
                     {
                         "id": "address",
                         "value": "000D6F000B5506AE"
                     },
                     {
                         "id": "allowjoin",
                         "value": false
                     },
                     {
                         "id": "jointimercount",
                         "value": 0
                     },
                     {
                         "id": "available",
                         "value": true
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "id": "address",
                         "type": "string",
                         "writable": false,
                         "label": "Address"
                     },
                     {
                         "type": "string",
                         "label": "Trust Center Key",
                         "id": "TCkey",
                         "writable": true,
                         "unit": "128bit HEX"
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Allow Join",
                         "id": "allowjoin",
                         "writable": true,
                         "fn_set": null,
                         "unit": "(60 second allow)"
                     },
                     {
                         "type": "number",
                         "default": 0,
                         "label": "join Timer count",
                         "id": "jointimercount",
                         "writable": false,
                         "unit": ".5 seconds"
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Available",
                         "id": "available",
                         "writable": false
                     }
                 ],
                 "uid": "via 1-1.3:1.0",
                 "type": "bridge"
             },
             {
                 "driver": "energy-dsmr4",
                 "name": "Iungo",
                 "oid": "538d72d9",
                 "propsval": [
                     {
                         "id": "name",
                         "value": "Iungo"
                     },
                     {
                         "id": "metertype",
                         "value": "XMX"
                     },
                     {
                         "id": "version",
                         "value": "5"
                     },
                     {
                         "id": "serial_e",
                         "value": "4530303335303033373832393338353136"
                     },
                     {
                         "id": "usage",
                         "value": 608
                     },
                     {
                         "id": "T1",
                         "value": 25046.573
                     },
                     {
                         "id": "T2",
                         "value": 20777.328
                     },
                     {
                         "id": "-T1",
                         "value": 223.173
                     },
                     {
                         "id": "-T2",
                         "value": 544.875
                     },
                     {
                         "id": "L1I",
                         "value": 3
                     },
                     {
                         "id": "L1U",
                         "value": 232
                     },
                     {
                         "id": "L1Pimp",
                         "value": 0.608
                     },
                     {
                         "id": "L1Pexp",
                         "value": 0
                     },
                     {
                         "id": "c_tariff",
                         "value": 2
                     },
                     {
                         "id": "serial_g",
                         "value": "4730303332353635353137303533393137"
                     },
                     {
                         "id": "gas_usage",
                         "value": 0
                     },
                     {
                         "id": "gas",
                         "value": 12005.221
                     },
                     {
                         "id": "Cost-T1",
                         "value": 0.2991
                     },
                     {
                         "id": "Cost-T2",
                         "value": 0.329774
                     },
                     {
                         "id": "Cost-nT1",
                         "value": 0
                     },
                     {
                         "id": "Cost-nT2",
                         "value": 0
                     },
                     {
                         "id": "netting",
                         "value": "off"
                     },
                     {
                         "id": "Cost-net-comp",
                         "value": 0
                     },
                     {
                         "id": "Cost-gas",
                         "value": 1.266991
                     },
                     {
                         "id": "Gas-interval",
                         "value": 292
                     },
                     {
                         "id": "Client-blob",
                         "value": ""
                     },
                     {
                         "id": "crc_err",
                         "value": 26
                     },
                     {
                         "id": "available",
                         "value": true
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "string",
                         "label": "Energy provider",
                         "id": "provider_e",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "id": "metertype",
                         "type": "string",
                         "label": "type"
                     },
                     {
                         "id": "version",
                         "type": "string",
                         "label": "SMR"
                     },
                     {
                         "type": "string",
                         "label": "E meter sn",
                         "id": "serial_e",
                         "persistent": true,
                         "logchange": true
                     },
                     {
                         "type": "number",
                         "label": "Energy usage",
                         "id": "usage",
                         "log": true,
                         "unit": "W"
                     },
                     {
                         "type": "number",
                         "log_interval": 30,
                         "label": "T1",
                         "id": "T1",
                         "log": true,
                         "cumulative": true,
                         "unit": "kWh"
                     },
                     {
                         "type": "number",
                         "log_interval": 30,
                         "label": "T2",
                         "id": "T2",
                         "log": true,
                         "cumulative": true,
                         "unit": "kWh"
                     },
                     {
                         "type": "number",
                         "log_interval": 30,
                         "label": "-T1",
                         "id": "-T1",
                         "log": true,
                         "cumulative": true,
                         "unit": "kWh"
                     },
                     {
                         "type": "number",
                         "log_interval": 30,
                         "label": "-T2",
                         "id": "-T2",
                         "log": true,
                         "cumulative": true,
                         "unit": "kWh"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L1 Current",
                         "id": "L1I",
                         "log": true,
                         "unit": "A"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L2 Current",
                         "id": "L2I",
                         "log": true,
                         "unit": "A"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L3 Current",
                         "id": "L3I",
                         "log": true,
                         "unit": "A"
                     },
                     {
                         "type": "number",
                         "label": "L1 Voltage",
                         "id": "L1U",
                         "log": true,
                         "unit": "V"
                     },
                     {
                         "type": "number",
                         "label": "L2 Voltage",
                         "id": "L2U",
                         "log": true,
                         "unit": "V"
                     },
                     {
                         "type": "number",
                         "label": "L3 Voltage",
                         "id": "L3U",
                         "log": true,
                         "unit": "V"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L1 Power Import",
                         "id": "L1Pimp",
                         "log": true,
                         "unit": "kW"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L2 Power Import",
                         "id": "L2Pimp",
                         "log": true,
                         "unit": "kW"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L3 Power Import",
                         "id": "L3Pimp",
                         "log": true,
                         "unit": "kW"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L1 Power Export",
                         "id": "L1Pexp",
                         "log": true,
                         "unit": "kW"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L2 Power Export",
                         "id": "L2Pexp",
                         "log": true,
                         "unit": "kW"
                     },
                     {
                         "type": "number",
                         "log_interval": 5,
                         "label": "L3 Power Export",
                         "id": "L3Pexp",
                         "log": true,
                         "unit": "kW"
                     },
                     {
                         "type": "number",
                         "log_interval": 30,
                         "label": "Tariff",
                         "id": "c_tariff",
                         "log": true,
                         "unit": "x"
                     },
                     {
                         "type": "string",
                         "label": "Gas meter sn",
                         "id": "serial_g",
                         "persistent": true,
                         "logchange": true
                     },
                     {
                         "type": "string",
                         "label": "Gas provider",
                         "id": "provider_g",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "number",
                         "label": "Gas usage",
                         "id": "gas_usage",
                         "log": true,
                         "unit": "m³"
                     },
                     {
                         "type": "number",
                         "label": "Gas total",
                         "id": "gas",
                         "log": true,
                         "cumulative": true,
                         "unit": "m³"
                     },
                     {
                         "log": true,
                         "type": "number",
                         "default": 0,
                         "label": "€ T1",
                         "id": "Cost-T1",
                         "writable": true,
                         "persistent": true,
                         "unit": "¤/kWh"
                     },
                     {
                         "log": true,
                         "type": "number",
                         "default": 0,
                         "label": "€ T2",
                         "id": "Cost-T2",
                         "writable": true,
                         "persistent": true,
                         "unit": "¤/kWh"
                     },
                     {
                         "log": true,
                         "type": "number",
                         "default": 0,
                         "label": "€ -T1",
                         "id": "Cost-nT1",
                         "writable": true,
                         "persistent": true,
                         "unit": "¤/kWh"
                     },
                     {
                         "log": true,
                         "type": "number",
                         "default": 0,
                         "label": "€ -T2",
                         "id": "Cost-nT2",
                         "writable": true,
                         "persistent": true,
                         "unit": "¤/kWh"
                     },
                     {
                         "type": "enum",
                         "default": "off",
                         "label": "netting",
                         "id": "netting",
                         "writable": true,
                         "range": "off,tgroup,hi-low",
                         "persistent": true
                     },
                     {
                         "type": "number",
                         "default": 0,
                         "label": "compensation",
                         "id": "Cost-net-comp",
                         "writable": true,
                         "persistent": true,
                         "unit": "¤/kWh"
                     },
                     {
                         "log": true,
                         "type": "number",
                         "default": 0,
                         "label": "€ Gas",
                         "id": "Cost-gas",
                         "writable": true,
                         "persistent": true,
                         "unit": "¤/m³"
                     },
                     {
                         "type": "number",
                         "default": 3600,
                         "label": "Gas interval",
                         "id": "Gas-interval",
                         "persistent": true,
                         "unit": "sec"
                     },
                     {
                         "type": "string",
                         "default": "",
                         "label": "Client-blob",
                         "id": "Client-blob",
                         "writable": true,
                         "persistent": true,
                         "hidden": true
                     },
                     {
                         "id": "crc_err",
                         "type": "number",
                         "writable": false,
                         "label": "crc errors"
                     },
                     {
                         "id": "available",
                         "type": "boolean",
                         "label": "Available"
                     }
                 ],
                 "uid": "-",
                 "type": "energy"
             },
             {
                 "driver": "bridge-gpio",
                 "name": "-",
                 "oid": "b7bae611",
                 "propsval": [
                     {
                         "id": "available",
                         "value": false
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Available",
                         "id": "available",
                         "writable": false
                     }
                 ],
                 "uid": "39",
                 "type": "bridge"
             },
             {
                 "driver": "bridge-gpio",
                 "name": "-",
                 "oid": "64fcd7dc",
                 "propsval": [
                     {
                         "id": "available",
                         "value": false
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Available",
                         "id": "available",
                         "writable": false
                     }
                 ],
                 "uid": "57",
                 "type": "bridge"
             },
             {
                 "driver": "smartbridge-uart",
                 "name": "-",
                 "oid": "36c1fc52",
                 "propsval": [
                     {
                         "id": "available",
                         "value": true
                     },
                     {
                         "id": "metertype",
                         "value": "Smart P1 DSMR 4"
                     },
                     {
                         "id": "bytes_rx",
                         "value": 2876841124
                     },
                     {
                         "id": "bytes_tx",
                         "value": 0
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Available",
                         "id": "available",
                         "writable": false
                     },
                     {
                         "fn_set": null,
                         "type": "enum",
                         "default": "-",
                         "label": "Metertype",
                         "id": "metertype",
                         "writable": true,
                         "range": "-,Smart P1,Smart P1 DSMR 
4,S1,IEC,analog,demo,modbus,gas only,Smart P1 SMR,DSMR double 
gas,dummy",
                         "persistent": true
                     },
                     {
                         "id": "bytes_rx",
                         "type": "number",
                         "writable": false,
                         "label": "Bytes received"
                     },
                     {
                         "id": "bytes_tx",
                         "type": "number",
                         "writable": false,
                         "label": "Bytes transmitted"
                     },
                     {
                         "type": "command",
                         "label": "Firmware",
                         "id": "fw-upgrade",
                         "writable": true,
                         "range": "upgrade",
                         "fn_set": null
                     },
                     {
                         "id": "message",
                         "type": "string",
                         "writable": false,
                         "label": "message"
                     }
                 ],
                 "uid": "/dev/ttyAPP:9600:e71",
                 "type": "bridge"
             },
             {
                 "driver": "bridge-usbuart",
                 "name": "-",
                 "oid": "285b91de",
                 "propsval": [
                     {
                         "id": "available",
                         "value": false
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "boolean",
                         "default": false,
                         "label": "Available",
                         "id": "available",
                         "writable": false
                     }
                 ],
                 "uid": "1-1.3:1.0;19200",
                 "type": "bridge"
             },
             {
                 "driver": "water-breakout",
                 "name": "Watermeter",
                 "oid": "40c3afff",
                 "propsval": [
                     {
                         "id": "name",
                         "value": "Watermeter"
                     },
                     {
                         "id": "flow",
                         "value": 5.5
                     },
                     {
                         "id": "pulstotal",
                         "value": 50845
                     },
                     {
                         "id": "kfact",
                         "value": 1000
                     },
                     {
                         "id": "offset",
                         "value": 1447.612
                     },
                     {
                         "id": "tariff",
                         "value": 0.5
                     },
                     {
                         "id": "connection",
                         "value": "breakout"
                     }
                 ],
                 "propertyInfo": [
                     {
                         "type": "string",
                         "label": "Name",
                         "id": "name",
                         "writable": true,
                         "persistent": true
                     },
                     {
                         "type": "number",
                         "default": 0,
                         "label": "water flow",
                         "id": "flow",
                         "log": true,
                         "unit": "l/min"
                     },
                     {
                         "type": "number",
                         "label": "totalWater",
                         "id": "pulstotal",
                         "writable": false,
                         "persistent": true,
                         "unit": "puls",
                         "default": 0,
                         "fn_edit": null,
                         "log": true,
                         "linkoppid": "kfact",
                         "cumulative": true
                     },
                     {
                         "type": "number",
                         "label": "Pulses/m3",
                         "id": "kfact",
                         "writable": true,
                         "persistent": true,
                         "unit": "puls/m³",
                         "min": 1,
                         "default": 1000,
                         "fn_set": null
                     },
                     {
                         "logchange": true,
                         "type": "number",
                         "default": 0,
                         "label": "offset",
                         "id": "offset",
                         "writable": true,
                         "persistent": true,
                         "unit": "m³"
                     },
                     {
                         "log": true,
                         "type": "number",
                         "default": 0,
                         "label": "Tariff",
                         "id": "tariff",
                         "writable": true,
                         "persistent": true,
                         "unit": "¤/m³"
                     },
                     {
                         "fn_set": null,
                         "type": "enum",
                         "default": "-",
                         "label": "Connection",
                         "id": "connection",
                         "writable": true,
                         "range": "-,breakout,breakout_ch2,counter",
                         "persistent": true
                     }
                 ],
                 "uid": "-",
                 "type": "water"
             }
         ]
     },
     "systime": 1733838742,
     "seq": 1,
     "error": false
}

Hoop dat je hier iets mee kunt....

Groeten,

Henk

**Comment by robertraaijmakers** [comment]
Hi Henk,

Heb je al geprobeerd om het device als een nieuw device toe te voegen via de add device button en dan type "water"?
Voor zover ik in jouw result terug zie zou hij hem namelijk gewoon moeten herkennen ongeacht of hij achter een breakout box hangt of niet omdat hij nog steeds onderwater als type "water" staat.

**Comment by henkbart** [comment]
Hallo Robert,

Dat had ik dus niet geprobeerd. Wel vroeger, maar toen was dat er niet.
Maar nu dus wel, en het werkt!!!.

Dus het probleem is opgelost.
Bedankt voor je support!!!!

Groeten,

Henk


------ Original Message ------
From: "Robert" ***@***.***>
To: "robertraaijmakers/com.iungo" ***@***.***>
Cc: "henkbart" ***@***.***>; "Mention" 
***@***.***>
Sent: 10-12-2024 15:25:36
Subject: Re: [robertraaijmakers/com.iungo] Water Meter (Issue #28)

**Comment by robertraaijmakers** [comment]
Top, super fijn om te horen! :)
