### ISSUE TITLE
Iungo is not updating the variables

### ISSUE THREAD

**Issue by GithubBram** [robertraaijmakers/com.iungo#29]
Iungo is not updating the variables in Homey

97fa43c2-ddb4-44b5-8842-2a47c62f71a7

Homey Pro 2023 10.3.0-rc.7

Iungo v1.0.4

**Comment by GithubBram** [comment]
![Iungo_not_updating](https://github.com/robertraaijmakers/com.iungo/assets/45642947/c9b36753-c16f-458e-b237-f5e932366d21)

**Comment by robertraaijmakers** [comment]
Hm, the discovery site seems to be down. My mobile Iungo app isn't working either :(

**Comment by GithubBram** [comment]
When I log in on the remote Iungo site (https://xxxxx.iungoconnect.eu/iungo/app/#/, not the local network Iungo app) it is working. So the issue is at Iungo site? In Homey I also use local API calls to Iungo to get variables that are not supported by the Homey app, e.g. for breakout box values.

**Comment by robertraaijmakers** [comment]
Yes, but the app uses another URL to get the local IP of the device. The URL the app uses is the same URL as that is used in their own Iungo mobile app. And that URL seemed to be down (and is now up again). My mobile app and the Homey app are both working again.

**Comment by GithubBram** [comment]
Yes confirmed, so the issue was on Iungo site. Thanks!
