### ISSUE TITLE
Beta Version 1.3

### ISSUE THREAD

**Issue by mruiter** [robertraaijmakers/com.iungo#7]
Water can not be added. It just gives a spinning wheel after selecting the iungo.

Solar and Enerycontroller adding was suc6ful

**Comment by robertraaijmakers** [comment]
Hi, thanks for reporting.

Can you please provide some more information regarding this issues? I don't owe a water meter myself so can't test it.

Do you see the water meter and then after selecting it you get the spinning wheel?

Can you provide one or more of the following, this will provide me some information to fix the issue:
- Check if there are any errors in the console log (debug window) of your browser (if you use a browser)
- http://<<your iungo ip>>/iungo/control/?cmd=api_form&method=objmgr_get_objects_with_values_and_metadata and post either all data (after clicking on the call method button) or only the part of the water meter.
- Run the app through command line and see if any errors are reported in the terminal/command prompt after/while adding the water meter

Thanks!

**Comment by mruiter** [comment]
The console debug gives a app crash with the adding of water:

``2017-08-30 14:04:54 [log] [ManagerDrivers] [energy_meter] [0] _syncDevice 538d72d9
{ 'abc-123':
   IungoRouter {
     domain: null,
     _events:
      { log: [Function: bound bound log],
        error: [Function: bound bound error],
        iungo_available: [Function],
        'refresh-538d72d9': [Function: bound syncDevice],
        'refresh-95778a43': [Function: bound syncDevice] },
     _eventsCount: 5,
     _maxListeners: 0,
     _debug: true,
     id: 'abc-123',
     address: 'http://192.168.0.253',
     name: 'IungoBox',
     modelId: 'default',
     modelName: undefined,
     icon: '/app/com.iungo/assets/images/routers/default.svg',
     _energyMeters: { '538d72d9': [Object] },
     _waterMeters: { '82ec52ad': [Object] },
     _sockets: {},
     _solarMeters: { '95778a43': [Object] },
     _client:
      { sid: null,
        username: '',
        password: '',
        options: [Object],
        sequence: 18 },
     _refreshInterval:
      Timeout {
        _called: true,
        _idleTimeout: 5000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 85946,
        _onTimeout: [Function: bound _refreshDevices],
        _timerArgs: undefined,
        _repeat: 5000,
        _destroyed: false,
        [Symbol(asyncId)]: 112,
        [Symbol(triggerAsyncId)]: 103 } } }
192.168.0.253
_initIungo
2017-08-30 14:04:59 [log] [App] [IungoRouter][abc-123] _refreshDevices
{ seq: 19, method: 'objmgr_get_objects_init', arguments: {} }
2017-08-30 14:04:59 [log] [ManagerDrivers] [energy_solar] [0] _syncDevice 95778a43
2017-08-30 14:04:59 [log] [ManagerDrivers] [energy_meter] [0] _syncDevice 538d72d9
onPairListDevices { connected: true,
  iungo:
   IungoRouter {
     domain: null,
     _events:
      { log: [Function: bound bound log],
        error: [Function: bound bound error],
        iungo_available: [Function],
        'refresh-538d72d9': [Function: bound syncDevice],
        'refresh-95778a43': [Function: bound syncDevice] },
     _eventsCount: 5,
     _maxListeners: 0,
     _debug: true,
     id: 'abc-123',
     address: 'http://192.168.0.253',
     name: 'IungoBox',
     modelId: 'default',
     modelName: undefined,
     icon: '/app/com.iungo/assets/images/routers/default.svg',
     _energyMeters: { '538d72d9': [Object] },
     _waterMeters: { '82ec52ad': [Object] },
     _sockets: {},
     _solarMeters: { '95778a43': [Object] },
     _client:
      { sid: null,
        username: '',
        password: '',
        options: [Object],
        sequence: 19 },
     _refreshInterval:
      Timeout {
        _called: true,
        _idleTimeout: 5000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 90956,
        _onTimeout: [Function: bound _refreshDevices],
        _timerArgs: undefined,
        _repeat: 5000,
        _destroyed: false,
        [Symbol(asyncId)]: 112,
        [Symbol(triggerAsyncId)]: 103 } } }
/drivers/water_meter/driver.js:66
                                data                    : { iungo_id: state.iungo.id, id: socket  },
                                                                                          ^

ReferenceError: socket is not defined
    at DriverWaterMeter.onPairListDevices (/drivers/water_meter/driver.js:66:47)
    at EventEmitter.socket.on.on (/drivers/water_meter/driver.js:40:11)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at i.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:2094)
    at DriverWaterMeter.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:4331)
    at Homey.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:2007)
    at SDK._onReady (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:969)
    at ManagerDrivers._onEventDriverPairMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/drivers.js:1:1926)
    at _eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1219)

--- INFO: com.iungo has been killed ---
``

**Comment by mruiter** [comment]
And i dont see the water meter... It just goes until the selecting the iungo. Then next and then a spinning wheel and the app crash

**Comment by robertraaijmakers** [comment]
Thanks, submitted the fix to the beta branch and send to Athom for approval. Should automatically update somewhere today / tomorrow probably.

**Comment by mruiter** [comment]
Haha , i was just creating a pull request for the socket 2 water_meter :)

Great app btw
