### ISSUE TITLE
Homey iungo werkt niet meer op homey 2.0

### ISSUE THREAD

**Issue by Hmvink** [robertraaijmakers/com.iungo#9]
Sinds de update naar Homey 2.0 tonen alle apparaten een rood uitroepteken en kunnen niet meer gebruikt worden. 

Ik zou het heel fijn vinden als ik ze met de nieuwe Insights functionaliteit kan uitlezen. 

Groeten, Hans Maarten Vink

**Comment by robertraaijmakers** [comment]
Hi Hans,

Vervelend om te horen. Zelf draait hij prima hier op 2.0. Wat je zou kunnen proberen is als volgt:

- Start Homey opnieuw op
- Zet de Iungo app uit via de settings
- Zet de Iungo app weer aan (en wacht even)
- Als bovenstaande allemaal niet werkt, probeer dan een reboot van Iungo en vervolgens een nieuw device toe te voegen via add devices (en kijk of je je Iungo er tussen ziet staan)
- Als dat alsnog niet werkt dan ben ik bang dat je de app even eraf moet gooien. Homey moet herstarten en daarna de app weer opnieuw moet installeren.

**Comment by Hmvink** [comment]
Hoi Robert,

Dank voor je snelle reactie!

Na een herstart van de iungo en de iungo opnieuw toegevoegd te hebben in de
Homey werkt alles weer. :-)

Stom dat ik dat zelf niet geprobeerd heb...

Fijn weekend,

Hans Maarten

Op za 9 feb. 2019 19:15 schreef Robert <notifications@github.com:
